# Generated by Django 4.1.1 on 2023-02-08 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myProject', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
