# Generated by Django 4.1.1 on 2023-02-09 11:54

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myProject', '0002_alter_user_contacts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='contacts',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), size=None),
        ),
    ]
