# Generated by Django 4.1.1 on 2023-02-28 14:44

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myProject', '0004_alter_user_contacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='messages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='participants',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255), null=True, size=None),
        ),
    ]
