# Generated by Django 4.1.1 on 2023-03-01 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myProject', '0006_delete_conversation_message_receiver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date_of_creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
