# Generated by Django 4.1.1 on 2023-03-08 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myProject', '0012_message_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='file',
            field=models.FileField(default=None, upload_to='media/messages/% Y/% m/% d/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(default='media/profile/profile.png', upload_to='media/profile'),
        ),
    ]
