# Generated by Django 4.1.1 on 2023-03-08 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myProject', '0013_message_file_alter_user_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='file',
            field=models.FileField(blank=True, default=None, null=True, upload_to='media/messages/% Y/% m/% d/'),
        ),
    ]
