# Generated by Django 4.1.1 on 2023-03-09 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myProject', '0014_alter_message_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messages', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='myProject.message')),
            ],
        ),
    ]
