# Generated by Django 4.1.1 on 2023-03-21 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myProject', '0015_signals'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Signals',
        ),
    ]
