export const LOGIN_SUCCES = 'LOGIN_SUCCES';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOAD_USER_SUCCES = 'LOAD_USER_SUCCES';
export const LOAD_USER_FAIL = 'LOAD_USER_FAIL';
export const AUTHENTICATION_SUCCESS = 'AUTHENTICATION_SUCCESS';
export const AUTHENTICATION_FAIL = 'AUTHENTICATION_FAIL';
export const LOGOUT = 'LOGOUT';